name: PayRespectV2
version: 'V2.3'
main: org.tibthink.payRespectV2.PayRespectV2
api-version: "1.21"
description: to pay respect to a fallen player

commands:
  Test:
    description: Tests to make sure the plugin works
  Freedom:
    description: you just cant do it anymore...