name: PayRespectV2
version: 'V2.7.2'
main: org.tibthink.payRespectV2.PayRespectV2
api-version: "1.21"
description: to pay respect to a fallen player

commands:
  Test:
    description: Tests to make sure the plugin works
    usage: /test
  Freedom:
    description: you just cant do it anymore...
    usage: /freedom
  FiringSquad:
    description: kills every player that is on the server (good for the start of a server)
    usage: /firingSquad
  DeathCount:
    description: shows how many times you have died
    usage: /deathCount
  DeathLeaderboard:
    description: shows everyones deaths in a list
    usage: /deathLeaderboard
  Pversion:
    description: shows the version of the plugin
    usage: /Pversion
    
  PayRespect:
    description: Main PayRespect command
    usage: /payrespect <version>
    permission: payrespectv2.use

permissions:
  payrespectv2.version:
    description: Allows checking the plugin version
    default: op
  payrespectv2.use:
    description: Allows using PayRespect commands
    default: true